#!/bin/bash
NFRPD="  conf_SNA"
NL="source \/usr\/local\/bin\/gsf\/scripts\/lib_sna.sh"
sed -i "s/\#NL/$NL\n\#NL/" /usr/local/bin/gsf/scripts/configuracion-inicial.sh
sed -i "s/\#NFRPD/$NFRPD\n\#NFRPD/" /usr/local/bin/gsf/scripts/configuracion-inicial.sh